export const backgroundPokemonTypes = [
  { name: "fire", color: "#EB6C6C" },
  { name: "bug", color: "#91AC22" },
  { name: "water", color: "#009ACB" },
  { name: "poison", color: "#7E00CB" },
  { name: "normal", color: "#B6B6B6" },
  { name: "rock", color: "#857D57" },
  { name: "ground", color: "#A77437" },
  { name: "fighting", color: "#BA114E" },
  { name: "ghost", color: "#6B2BF1" },
  { name: "psychic", color: "#C4484A" },
  { name: "ice", color: "#3A9D90" },
  { name: "dragon", color: "#1268B8" },
  { name: "dark", color: "#373737" },
  { name: "fairy", color: "#C01A8D" },
  { name: "electric", color: "#B7B117" },
  { name: "steel", color: "#448F85" },
  { name: "grass", color: "#1EBA11" },
  { name: "flying", color: "linear-gradient(to right, #CBE9FF, #2299EE)" },
];

export const backgroundPokemonTagTypes = [
  { name: "fire", color: "#FF6464" },
  { name: "bug", color: "#C9FF84" },
  { name: "water", color: "#9FF3FF" },
  { name: "poison", color: "#D89CFD" },
  { name: "normal", color: "#CBCBCB" },
  { name: "rock", color: "#CFC06F" },
  { name: "ground", color: "#FFBF72" },
  { name: "fighting", color: "#FF699F" },
  { name: "ghost", color: "#B592FF" },
  { name: "psychic", color: "#FF5E60" },
  { name: "ice", color: "#AEFFF4" },
  { name: "dragon", color: "#87C5FF" },
  { name: "dark", color: "#8F8F8F" },
  { name: "fairy", color: "#FFA2E3" },
  { name: "electric", color: "#FFFA86" },
  { name: "steel", color: "#A4FFE9" },
  { name: "grass", color: "#80E177" },
  { name: "flying", color: "linear-gradient(to right, #CBE9FF, #2299EE)" },
];
